import "../styles/globals.css";
import Head from "next/head";
import "tailwindcss/tailwind.css";
import { AppProvider } from "../data/context/AppContext";

function MyApp({ Component, pageProps }) {
  return (
    <AppProvider>
      <div>
        <Head>
          <title>Next Admin</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </div>
    </AppProvider>
  );
}

export default MyApp;
