import "../styles/globals.css";
import Head from "next/head";
import "tailwindcss/tailwind.css";
import { AppProvider } from "../data/context/AppContext";
import { AuthProvider } from "../data/context/AuthContext";

function MyApp({ Component, pageProps }) {
  return (
    <AuthProvider>
      <AppProvider>
        <div>
          <Head>
            <title>Next Admin</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component {...pageProps} />
        </div>
      </AppProvider>
    </AuthProvider>
  );
}

export default MyApp;
